// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/loak155/techbranch-backend/internal/article/repository"
	"github.com/loak155/techbranch-backend/internal/article/router"
	"github.com/loak155/techbranch-backend/internal/article/usecase"
	"github.com/loak155/techbranch-backend/internal/pkg/config"
	"github.com/loak155/techbranch-backend/internal/pkg/db"
	"github.com/loak155/techbranch-backend/proto/article"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitServer(conf *config.Config, grpcServer *grpc.Server) (article.ArticleServiceServer, error) {
	gormDB := db.NewArticleDB(conf)
	iArticleRepository := repository.NewArticleRepository(gormDB)
	iArticleUsecase := usecase.NewArticleUsecase(iArticleRepository)
	articleServiceServer := router.NewArticleGRPCServer(grpcServer, iArticleUsecase)
	return articleServiceServer, nil
}
